import {CONFIG} from './config.js?v=16';import {auth} from './auth.js?v=16';import {uploadPhoto,removePhoto,signedPhotoUrl} from './storage.js?v=16';import {boxes as seedBoxes,items as seedItems,categories,locations} from './seed.js?v=16';
const base=CONFIG.supabaseUrl.replace(/\/$/,'');const modeKey='daktent-mode';
const uuid=id=>/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(id||'')?id:crypto.randomUUID();
const toRow=x=>({id:uuid(x.id),name:x.name,description:x.description||'',quantity:Number(x.quantity)||1,category:x.category,box_number:x.box||null,storage_location:x.storageLocation,travel_location:x.travelLocation,current_location:x.currentLocation||x.storageLocation||'Trailer',note:x.note||'',departure:!!x.departure,checked:!!x.checked,stock:x.stock||'n.v.t.',photos:(x.photos||[]).map(({id,path,name})=>({id,path,name})),product_weight_kg:num(x.productWeight),measured_weight_kg:num(x.measuredWeight),calculated_weight_kg:num(x.calculatedWeight),weight_source:x.weightSource||'',weight_verified:!!x.weightVerified,weight_date:x.weightDate||null,trailer_zone:x.trailerZone||null,position_x_cm:num(x.positionX),position_y_cm:num(x.positionY),packing_heavy:!!x.packingHeavy,packing_fragile:!!x.packingFragile,packing_liquid:!!x.packingLiquid,packing_accessible:!!x.packingAccessible,updated_at:new Date().toISOString()});
const fromRow=x=>({id:x.id,name:x.name,description:x.description||'',quantity:x.quantity,category:x.category,box:x.box_number,storageLocation:x.storage_location,travelLocation:x.travel_location,currentLocation:x.current_location,note:x.note||'',departure:x.departure,checked:x.checked,stock:x.stock,photos:x.photos||[],productWeight:x.product_weight_kg,measuredWeight:x.measured_weight_kg,calculatedWeight:x.calculated_weight_kg,weightSource:x.weight_source||'',weightVerified:x.weight_verified,weightDate:x.weight_date,trailerZone:x.trailer_zone,positionX:x.position_x_cm,positionY:x.position_y_cm,packingHeavy:x.packing_heavy,packingFragile:x.packing_fragile,packingLiquid:x.packing_liquid,packingAccessible:x.packing_accessible,createdAt:x.created_at,updatedAt:x.updated_at});
const num=v=>v===''||v==null?null:Number(v);
class SupabaseStore{
 async headers(extra={}){const s=await auth.refresh();if(!s)throw new Error('AUTH_REQUIRED');return{apikey:CONFIG.supabasePublishableKey,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json',...extra}}
 async request(path,opt={}){const r=await fetch(`${base}/rest/v1/${path}`,{...opt,headers:{...(await this.headers()),...opt.headers}});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.message||e.hint||`Supabase-fout ${r.status}`)}return r.status===204?null:r.json()}
 async ensureSeed(){const [existingBoxes,existingItems]=await Promise.all([this.request('boxes?select=id&limit=1'),this.request('items?select=id&limit=1')]);if(!existingBoxes.length)await this.request('boxes',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(seedBoxes.map(b=>({...b,current_location:b.id===4?'Thuis':'Trailer'})))});if(!existingItems.length){const rows=seedItems.map(x=>toRow({...x,id:null}));await this.request('items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(rows)})}}
 async snapshot(){await this.ensureSeed();const [rawItems,rawBoxes,technical,hitchMeasurements,safetyChecks,trips,tripSnapshots,maintenance]=await Promise.all([this.request('items?select=*&order=name'),this.request('boxes?select=*&order=id'),this.request('technical_values?select=*&order=key'),this.request('hitch_measurements?select=*&order=measured_at.desc,created_at.desc'),this.request('safety_checks?select=*&order=sort_order'),this.request('trip_profiles?select=*&order=created_at.desc'),this.request('trip_snapshots?select=*&order=captured_at.desc'),this.request('maintenance?select=*&order=next_date.asc.nullslast,component')]);const items=await Promise.all(rawItems.map(async row=>{const x=fromRow(row);x.photos=await Promise.all(x.photos.map(async p=>({...p,url:await signedPhotoUrl(p.path).catch(()=>null)})));return x}));const boxes=await Promise.all(rawBoxes.map(async box=>({...box,photos:await Promise.all((box.photos||[]).map(async p=>({...p,url:await signedPhotoUrl(p.path).catch(()=>null)})))})));return{boxes,items,technical,hitchMeasurements,safetyChecks,trips,tripSnapshots,maintenance,categories,locations,mode:localStorage.getItem(modeKey)||'storage'}}
 async setMode(mode){localStorage.setItem(modeKey,mode)}
 async saveItem(item){const row=toRow(item);const exists=Boolean(item.id&&/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(item.id));const path=exists?`items?id=eq.${encodeURIComponent(item.id)}`:'items';const result=await this.request(path,{method:exists?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});if(item.box)await this.request(`boxes?id=eq.${item.box}&measured_weight_kg=not.is.null`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({contents_changed_since_weighing:true})});return fromRow(result[0])}
 async deleteItem(id){const item=(await this.snapshot()).items.find(x=>x.id===id);for(const p of item?.photos||[])await removePhoto(p.path).catch(()=>{});await this.request(`items?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});if(item?.box)await this.request(`boxes?id=eq.${item.box}&measured_weight_kg=not.is.null`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({contents_changed_since_weighing:true})})}
 async toggleCheck(id){const rows=await this.request(`items?id=eq.${encodeURIComponent(id)}&select=checked`);if(rows[0])await this.request(`items?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({checked:!rows[0].checked,updated_at:new Date().toISOString()})})}
 async resetCheck(){await this.request('items?departure=eq.true',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({checked:false,updated_at:new Date().toISOString()})})}
 async addPhoto(id,file){const blob=await compress(file),photoId=crypto.randomUUID(),path=`${id}/${photoId}.jpg`;await uploadPhoto(path,blob);const rows=await this.request(`items?id=eq.${encodeURIComponent(id)}&select=*`),item=fromRow(rows[0]);item.photos.push({id:photoId,path,name:file.name});await this.saveItem(item)}
 async deletePhoto(itemId,photoId){const rows=await this.request(`items?id=eq.${encodeURIComponent(itemId)}&select=*`),item=fromRow(rows[0]),photo=item.photos.find(p=>p.id===photoId);if(photo)await removePhoto(photo.path);item.photos=item.photos.filter(p=>p.id!==photoId);await this.saveItem(item)}
 async addBoxPhoto(boxId,file){const blob=await compress(file),photoId=crypto.randomUUID(),path=`boxes/${boxId}/${photoId}.jpg`;await uploadPhoto(path,blob);const rows=await this.request(`boxes?id=eq.${boxId}&select=photos`),photos=rows[0]?.photos||[];photos.push({id:photoId,path,name:file.name});await this.request(`boxes?id=eq.${boxId}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({photos})})}
 async deleteBoxPhoto(boxId,photoId){const rows=await this.request(`boxes?id=eq.${boxId}&select=photos`),photos=rows[0]?.photos||[],photo=photos.find(p=>p.id===photoId);if(photo)await removePhoto(photo.path);await this.request(`boxes?id=eq.${boxId}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({photos:photos.filter(p=>p.id!==photoId)})})}
 async setBoxCurrentLocation(boxId,location){await Promise.all([this.request(`boxes?id=eq.${boxId}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({current_location:location})}),this.request(`items?box_number=eq.${boxId}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({current_location:location,updated_at:new Date().toISOString()})})])}
 async saveBoxLoading(boxId,weight,zone){const rows=await this.request(`items?box_number=eq.${boxId}&select=measured_weight_kg,product_weight_kg,calculated_weight_kg`),itemWeight=rows.reduce((s,x)=>s+Number(x.measured_weight_kg??x.product_weight_kg??x.calculated_weight_kg??0),0);await this.request(`boxes?id=eq.${boxId}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({measured_weight_kg:num(weight),weight_date:weight?new Date().toISOString().slice(0,10):null,weight_source:weight?'Eigen meting':'',contents_changed_since_weighing:false,item_weight_at_weighing_kg:weight?itemWeight:null,trailer_zone:zone||null})})}
 async addHitchMeasurement(value,date,note){await this.request('hitch_measurements',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({value_kg:Number(value),measured_at:date||new Date().toISOString().slice(0,10),source:'ATSensoTec STB-200',note:note||''})})}
 async toggleSafety(id,checked){await this.request(`safety_checks?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({checked,checked_at:checked?new Date().toISOString():null})})}
 async resetSafety(){await this.request('safety_checks?checked=eq.true',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({checked:false,checked_at:null})})}
 async addTrip(o){o.start_date=o.start_date||null;o.end_date=o.end_date||null;if(o.active)await this.request('trip_profiles?active=eq.true',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({active:false})});await this.request('trip_profiles',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(o)})}
 async addTripSnapshot(o){await this.request('trip_snapshots',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(o)})}
 async saveMaintenance(id,o){o.last_date=o.last_date||null;o.next_date=o.next_date||null;await this.request(`maintenance?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(o)})}
 async export(){return new Blob([JSON.stringify(await this.snapshot(),null,2)],{type:'application/json'})}
 async resetAll(){throw new Error('Voorbeelddata herstellen is uitgeschakeld voor de centrale database')}
}
async function compress(file){const img=await createImageBitmap(file);const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Foto verwerken mislukt')),'image/jpeg',.78))}
export const store=new SupabaseStore();
